### ISSUE TITLE
Library for v15

### ISSUE THREAD

**Issue by vlorenzoPVH** [rexhip/rexhip#2]
Hi, 

Thank you so much for your effort and time.
I don't know if updated it to TIA Portal V15 version will be a easy thing... but it will reeeeally help!

Thank you again,

**Comment by rexhip** [comment]
Hi.
Thank you for your feedback. I been wrestling a bit with myself which version to use. Since there isn't any way to downgrade a library file, I chose v14 so these users may use it as well.

Upgrading a library file however is super easy, TIA-portal will ask you to upgrade when you retrieve a library file. So just click yes and you are good.

**Comment by vlorenzoPVH** [comment]
Thank you for your help! It worked perfectly!
