### ISSUE TITLE
Access to an optimized memory area is not permitted at this point.

### ISSUE THREAD

**Issue by Spawnsen** [rexhip/rexhip#3]
Hello,

I have the following error when translating:
Access to an optimized memory area is not permitted at this point. (mb_query Line: 49,88,114)
----------------------------------------------
![image](https://user-images.githubusercontent.com/4910440/67660724-bb3c2080-f95f-11e9-9c35-9eb6ce56f505.png)
----------------------------------------------
![image](https://user-images.githubusercontent.com/4910440/67660745-c98a3c80-f95f-11e9-8c1a-1025f503dedd.png)
----------------------------------------------
![image](https://user-images.githubusercontent.com/4910440/67660769-dd35a300-f95f-11e9-80ac-7d2cd41cb437.png)
----------------------------------------------
For which DB do I have to deactivate the optimized access?

Thank you

**Comment by Spawnsen** [comment]
I have deactivated the optimized access of mb_client_ctrl and now it works.
Is this set automatically by my program?

**Comment by rexhip** [comment]
Hi Spawnsen. Thanks for showing interest in the library. 

Please can you post TIA-portal version, and the firmware you are using? Also please tell what do you mean by "translating"? It shouldn't be needed to manually deactivate optimized access for any block.

Kind regards,

**Comment by rexhip** [comment]
I been looking more in to the issue. The Rexhip library require firmware >= 4.2 for S7-1200, and >= 2.0 for S7-1500.

Unfortunately there has been a bug in TIA-portal when upgrading a plc firmware in a project. The  particular error messages will not go away. Instead of upgrading, you need to add a new plc to the project, and then import the library and your program to that new plc. I am using v14, so this bug may have been fixed in later versions

You write that the error went away when you disable optimized access for mb_client_ctrl. I haven't been able to reproduce this, but great if it works for you.
