### ISSUE TITLE
Expose busy as output variable in SB

### ISSUE THREAD

**Issue by gitneko** [rexhip/rexhip#8]
Currently one is not able to check whether a current station block is busy (as in trying to read or write data), this is not exposed directly. However the PLCOpen standard says that async FBs should have a busy output parameter.

I'd like to propose to expose the `busy` state just like the `Finnish` or `Error` variables in the `sb.out` struct, so implementors can easily expose whether the remote device is currently getting queried or not.

I've tried to "hack" this together in my own SB by accessing internal variables
```
IF #mb_query.z.q.mb_addr = #mb_addr THEN
    #isBusy := #mb_query.stat.busy;
END_IF;
```
I'm currently not sure if this works at all, since I'm only able to test this next week.

However I still don't think accessing internal variables is good and thus would like to propose to expose this easily through the library itself.

**Comment by rexhip** [comment]
Hi gitneko

In the «hack» you wrote, there is no code that reset `isBusy`, apart from that I believe it will work for rtu, for tcp you also need to test for `#mb_query.z.run.state = 3`.  Keep in mind that `isBusy` will be set true on the next scan when execution starts, because, `busy` is set in the ctrl-block, which will execute on the next scan. You may try this:
```
#isBusy :=  (#mb_query.stat.busy or #mb_query.z.run.state = 3) 
    and  #mb_query.z.q.mb_addr = #mb_addr ;
```    
The problem with adding new features to the core blocks, is that takes memory, and memory is precious on the smallest S7-1200 PLC’s. I am not deaf to new features to the core, but I am cautious. Part of the philosophy in the library is that execution happen behind the scene. In Ethernet, you don’t know exactly when a packet is processed and send, but you know that the OS will take care of it in the background. 

Please may you give some example on a PLC-program that need information on when a sb is currently executing a query? You may already read it in the documentation, but just one (by default) query is executed at each cycle in a sb.  This mean that `isBusy` will only be true for small time slots. Perhaps one way to implement this is to have the functionality in a separate FC.

If you like to check if a query has just finished, then you may use: `#mb_query.Done`
```
#mb_query( ...query_params... ):
IF #mb_query.Done THEN // Done refer to the query above.
        query_cnt += 1;
END_IF;
```
Again, I am thankful for feedback, though I am a bit skeptical to this feature in core. Please can you provide some example on how you will use `isBusy`?

I agree with you on that accessing internal variables is not good practice, I may do changes to internal api’s.

**Comment by rexhip** [comment]
[mb_busy_sb.scl.txt](https://github.com/rexhip/rexhip/files/7758677/mb_busy_sb.scl.txt)
Code isn't tested, but I believe it will work. I may add this fc to the library if you have some good examples on where it is needed.

**Comment by gitneko** [comment]
Hello

Thank you for getting back to me.

Most of the time this would be used for debugging/informative purpose and to be PLCOpen compliant. Other than that this could be used in case the modbus device first needs to be configured, so you could use a falling edge on busy and the error flag to check whether the device has been configured, before actually reading and writing any operational data (I've had to do that before in the case of a fan with integrated frequency inverter).

I'd be great if this function can be added to the library, so everyone can use this if they want or need to.

**Comment by rexhip** [comment]
For debugging I recommend look at the counters inside `#sb.log`, if only done_cnt is running, then everything is fine for that sb. If comm. counter is running, then there is some communication problem. If the exception counter is incrementing, then one or more queries have wrong parameters. `error_data_addr` will tell which query causes the error.

To make some configurations queries go first, I recommend use `#mb_query.Done` with some logic. E.g:
```
CASE #state OF
    0: // Config query 1
        #mb_query( … );
        #state += BOOL_TO_INT( #mb_query.Done );
    1: // Config query 2
        #mb_query( … );
        #state += BOOL_TO_INT( #mb_query.Done );
ELSE 
   // Queries after configuration 
   #mb_query( … );
   #mb_query( … );
   #mb_query( … );

  IF #sb.out.communication_error THEN
     #state := 0;
  END_IF;
END_CASE;
```

Being PLCopen compliant would be nice, but as I write above, a busy flag would be set true the scan after a query has been inserted, and then I don’t find this feature so useful. I am sorry, but for now I will not include this feature request.

The `Finish` flag is true in one scan after execution is handed over to the next sb, it doesn't necessarily mean that all queries have been executed in a particular sb.
